# This is a basic workflow to help you get started with Actions

name: frontend-cypress.yml

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


defaults:
    run:
        working-directory: Front
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:3.8.3
    steps:
          - name: Checkout
            uses: actions/checkout@v1
            with:
              start: |
                npm start
                npm cypress:open
              working-directory : Front
              wait-on: 'http://localhost:3000'
              config: baseUrl=https://localhost:3000